DROP TABLE REPLY;
DROP TABLE REPORT;
DROP TABLE MEMBER;
DROP TABLE IMAGE;
DROP TABLE FEED;
DROP TABLE FRIEND;
DROP TABLE SEARCH;
DROP TABLE BOARD;
DROP TABLE LIKE_TABLE;
DROP TABLE CHOICE;
DROP TABLE CHAT_ROOM_JOIN;
DROP TABLE CHAT_ROOM;
DROP TABLE CHAT_MESSAGE;


CREATE TABLE "REPLY" (
	"REPLY_NO" NUMBER NOT NULL,
	"REPLY_WRITER" NUMBER NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(1500) NOT NULL,	
    "REPLY_FNO" NUMBER NOT NULL, 
    "ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL,
    "STATUS" VARCHAR2(2) DEFAULT 'Y' NOT NULL
);

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER NOT NULL,
	"REPORT_WRITER"	NUMBER NOT NULL,
	"REPORT_TITLE" VARCHAR2(200) NOT NULL,
    "REPORT_CONTENT" VARCHAR2(3000) NOT NULL,
	"ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL,
    "REPORT_STATUS" VARCHAR2(5) NOT NULL,
    "REPORT_TARGET" NUMBER DEFAULT 0,
    "REPORT_FNO" NUMBER DEFAULT 0
);

CREATE TABLE "MEMBER" (
	"USER_NO" NUMBER NOT NULL,
	"USER_ID" VARCHAR2(100)	NOT NULL,
	"USER_PWD" VARCHAR(100) NOT NULL,
	"USER_NAME"	VARCHAR(100) NOT NULL,
	"USER_NICK"	VARCHAR2(100) NOT NULL,
	"USER_PHONE" VARCHAR2(20) NOT NULL,
	"USER_EMAIL" VARCHAR2(100) NOT NULL,
	"USER_MBTI"	VARCHAR2(40) DEFAULT NULL,
	"ENROLL_DATE" DATE	DEFAULT	SYSDATE NOT NULL,
    "USER_BIRTHDAY" DATE NOT NULL,
	"ENABLE" VARCHAR2(2) DEFAULT 'Y' NOT NULL,
    "WB_STATUS" VARCHAR2(2) DEFAULT 'N' NOT NULL,
    "STATUS" VARCHAR2(5) DEFAULT 'Y' NOT NULL,
    "CHECK_LOGIN" VARCHAR2(10) DEFAULT 'N' NOT NULL
);

CREATE TABLE "IMAGE" (
	"FILE_NO" NUMBER NOT NULL,
	"FILE_WRITER" NUMBER NOT NULL,
    "ORIGIN_NAME" VARCHAR2(200) NOT NULL,
	"CHANGE_NAME" VARCHAR(200) NOT NULL,
	"FILE_PATH"	VARCHAR(1000) NOT NULL,
	"STATUS" VARCHAR2(2) DEFAULT 'Y' NOT NULL,
	"FILE_LEVEL" NUMBER	NOT NULL,
    "FILE_FNO" NUMBER DEFAULT NULL
);

CREATE TABLE "FEED" (
	"FEED_NO" NUMBER NOT NULL,
	"FEED_WRITER" NUMBER NOT NULL,
    "FEED_CONTENT" VARCHAR2(3000),
    "LIKE_STATUS" VARCHAR2(2) DEFAULT 'N' NOT NULL,
	"CHOICE_STATUS" VARCHAR(2) DEFAULT 'N' NOT NULL,
	"LIKE_COUNT" NUMBER DEFAULT 0 NOT NULL,
    "FEED_HASHTAG" VARCHAR(200)
);

CREATE TABLE "FRIEND" (
	"FRIEND_NO"	NUMBER NOT NULL,
    "FRIEND_USER1" NUMBER NOT NULL,
    "FRIEND_USER2" NUMBER NOT NULL,
    "ENABLE" VARCHAR2(2) DEFAULT 'Y' NOT NULL
);

CREATE TABLE "SEARCH" (
	"SEARCH_NO"	NUMBER NOT NULL,
	"SEARCH_WRITER" NUMBER NOT NULL,
	"SEARCH_KEYWORD" VARCHAR(1000) NOT NULL,
	"ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE "BOARD" (
	"BOARD_NO" NUMBER NOT NULL,
	"BOARD_WRITER" NUMBER NOT NULL,
    "BOARD_ACCEPTUSER" NUMBER NOT NULL,
	"BOARD_CONTENT"	VARCHAR(1500) NOT NULL,
    "BOARD_TYPE" VARCHAR(10) NOT NULL
);

CREATE TABLE LIKE_TABLE (
	"LIKE_NO" NUMBER NOT NULL,
	"LIKE_FNO" NUMBER NOT NULL,
	"LIKE_MEMBER" NUMBER NOT NULL,
    "LIKE_STATUS" VARCHAR2(2) DEFAULT 'N' NOT NULL
);

CREATE TABLE "CHOICE" (
	"CHOICE_NO" NUMBER NOT NULL,
	"CHOICE_FNO" NUMBER NOT NULL,
	"CHOICE_MEMBER" NUMBER NOT NULL,
    "CHOICE_STATUS" VARCHAR(2) DEFAULT 'N' NOT NULL
);

CREATE TABLE "CHAT_ROOM_JOIN" (
	"CHAT_ROOM_NO" NUMBER NOT NULL,
	"CHAT_USER_NO" NUMBER NOT NULL
);

CREATE TABLE "CHAT_ROOM" (
	"CHAT_ROOM_NO" NUMBER NOT NULL,
	"CHAT_USER_NO" NUMBER NOT NULL,
	"CHAT_TITLE" VARCHAR2(200) NOT NULL,
	"STATUS" VARCHAR(2) DEFAULT 'Y'	NOT NULL
);

CREATE TABLE "CHAT_MESSAGE" (
	"CHAT_NO" NUMBER NOT NULL,
	"CHAT_ROOM_NO" NUMBER NOT NULL,
	"CHAT_USER_NO" NUMBER NOT NULL,
    "CHAT_MESSAGE" VARCHAR2(200) NOT NULL,
	"ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL,
    "FEED_NO" NUMBER DEFAULT 0 NOT NULL
);

DROP SEQUENCE SEQ_REPLY_NO; 
DROP SEQUENCE SEQ_REPORT_NO; 
DROP SEQUENCE SEQ_MEMBER_NO; 
DROP SEQUENCE SEQ_FILE_NO; 
DROP SEQUENCE SEQ_FEED_NO; 
DROP SEQUENCE SEQ_FRIEND_NO; 
DROP SEQUENCE SEQ_SEARCH_NO;
DROP SEQUENCE SEQ_BOARD_NO; 
DROP SEQUENCE SEQ_LIKE_NO; 
DROP SEQUENCE SEQ_CHOICE_NO; 
DROP SEQUENCE SEQ_CHAT_ROOM_NO;
DROP SEQUENCE SEQ_CHAT_NO; 

/* 시퀀스 */
CREATE SEQUENCE SEQ_REPLY_NO NOCACHE; -- REPLY
CREATE SEQUENCE SEQ_REPORT_NO NOCACHE; -- REPORT
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- MEMBER
CREATE SEQUENCE SEQ_FILE_NO NOCACHE; -- IMAGE
CREATE SEQUENCE SEQ_FEED_NO NOCACHE; --FEED
CREATE SEQUENCE SEQ_FRIEND_NO NOCACHE; -- FRIEND
CREATE SEQUENCE SEQ_SEARCH_NO NOCACHE; -- SEARCH
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; -- BOARD
CREATE SEQUENCE SEQ_LIKE_NO NOCACHE; -- LIKE
CREATE SEQUENCE SEQ_CHOICE_NO NOCACHE; -- CHOICE
CREATE SEQUENCE SEQ_CHAT_ROOM_NO NOCACHE; -- CHAT_ROOM 
CREATE SEQUENCE SEQ_CHAT_NO NOCACHE; -- CHAT_MESSAGE


/* PK, FK 설정 */
ALTER TABLE REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY (
    REPLY_NO
);

ALTER TABLE REPORT ADD CONSTRAINT PK_REPORT PRIMARY KEY (
	REPORT_NO
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	USER_NO
);

ALTER TABLE IMAGE ADD CONSTRAINT PK_IMAGE PRIMARY KEY (
	FILE_NO
);

ALTER TABLE FEED ADD CONSTRAINT PK_FEED PRIMARY KEY (
	FEED_NO
);

ALTER TABLE FRIEND ADD CONSTRAINT PK_FRIEND PRIMARY KEY (
	FRIEND_NO
);

ALTER TABLE SEARCH ADD CONSTRAINT PK_SEARCH PRIMARY KEY (
	SEARCH_NO
);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	BOARD_NO
);

ALTER TABLE LIKE_TABLE ADD CONSTRAINT PK_LIKE_TABLE PRIMARY KEY (
	LIKE_NO
);

ALTER TABLE CHOICE ADD CONSTRAINT PK_CHOICE PRIMARY KEY (
	CHOICE_NO
);

ALTER TABLE CHAT_ROOM ADD CONSTRAINT PK_CHAT_ROOM PRIMARY KEY (
	CHAT_ROOM_NO
);

ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT PK_CHAT_MESSAGE PRIMARY KEY (
	CHAT_NO
);


/* 칼럼명 */
-- REPLY 테이블
COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글번호';
COMMENT ON COLUMN REPLY.REPLY_WRITER IS '댓글작성자';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN REPLY.REPLY_FNO IS '게시글번호';
COMMENT ON COLUMN REPLY.ENROLL_DATE IS '작성일';
COMMENT ON COLUMN REPLY.STATUS IS '상태';


-- REPORT 테이블
COMMENT ON COLUMN REPORT.REPORT_NO IS '신고번호';
COMMENT ON COLUMN REPORT.REPORT_WRITER IS '신고작성자';
COMMENT ON COLUMN REPORT.REPORT_TITLE IS '신고제목';
COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '신고내용';
COMMENT ON COLUMN REPORT.ENROLL_DATE IS '신고작성일';
COMMENT ON COLUMN REPORT.REPORT_STATUS IS '읽음상태';
COMMENT ON COLUMN REPORT.REPORT_TARGET IS '신고유저번호';
COMMENT ON COLUMN REPORT.REPORT_FNO IS '신고게시물번호';


-- MEMBER 테이블
COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.USER_NICK IS '회원닉네임';
COMMENT ON COLUMN MEMBER.USER_PHONE IS '회원휴대폰';
COMMENT ON COLUMN MEMBER.USER_EMAIL IS '회원이메일';
COMMENT ON COLUMN MEMBER.USER_MBTI IS 'MBTI';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.USER_BIRTHDAY IS '회원생일(나이)';
COMMENT ON COLUMN MEMBER.ENABLE IS '차단상태';
COMMENT ON COLUMN MEMBER.WB_STATUS IS '인플루언서등급';
COMMENT ON COLUMN MEMBER.STATUS IS '블랙리스트등급';


-- IMAGE 테이블
COMMENT ON COLUMN IMAGE.FILE_NO IS '파일번호';
COMMENT ON COLUMN IMAGE.FILE_WRITER IS '파일작성자';
COMMENT ON COLUMN IMAGE.ORIGIN_NAME IS '파일원본이름';
COMMENT ON COLUMN IMAGE.CHANGE_NAME IS '파일수정이름';
COMMENT ON COLUMN IMAGE.FILE_PATH IS '파일저장경로';
COMMENT ON COLUMN IMAGE.FILE_LEVEL IS '파일종류';
COMMENT ON COLUMN IMAGE.STATUS IS '파일상태';


-- FEED 테이블
COMMENT ON COLUMN FEED.FEED_NO IS '피드번호';
COMMENT ON COLUMN FEED.FEED_WRITER IS '피드작성자';
COMMENT ON COLUMN FEED.LIKE_STATUS IS '피드좋아요상태';
COMMENT ON COLUMN FEED.CHOICE_STATUS IS '피드찜상태';
COMMENT ON COLUMN FEED.LIKE_COUNT IS '피드좋아요숫자';
COMMENT ON COLUMN FEED.FEED_HASHTAG IS '해시태그';


-- FRIEND 테이블
COMMENT ON COLUMN FRIEND.FRIEND_NO IS '친구번호';
COMMENT ON COLUMN FRIEND.FRIEND_USER1 IS '친구1유저';
COMMENT ON COLUMN FRIEND.FRIEND_USER2 IS '친구2유저';
COMMENT ON COLUMN FRIEND.ENABLE IS '차단상태';


-- SEARCH 테이블
COMMENT ON COLUMN SEARCH.SEARCH_NO IS '검색번호';
COMMENT ON COLUMN SEARCH.SEARCH_WRITER IS '검색하는유저';
COMMENT ON COLUMN SEARCH.SEARCH_KEYWORD IS '검색키워드';
COMMENT ON COLUMN SEARCH.ENROLL_DATE IS '검색기록시간';


-- BOARD 테이블
COMMENT ON COLUMN BOARD.BOARD_NO IS '알림번호';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '알림작성자';
COMMENT ON COLUMN BOARD.BOARD_ACCEPTUSER IS '알림받는사람';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '알림내용';
COMMENT ON COLUMN BOARD.BOARD_TYPE IS '알림종류';



-- LIKE 테이블
COMMENT ON COLUMN LIKE_TABLE.LIKE_NO IS '좋아요번호';
COMMENT ON COLUMN LIKE_TABLE.LIKE_FNO IS '좋아요누른피드';
COMMENT ON COLUMN LIKE_TABLE.LIKE_MEMBER IS '좋아요누른유저';
COMMENT ON COLUMN LIKE_TABLE.LIKE_STATUS IS '좋아요상태';


-- CHOICE 테이블
COMMENT ON COLUMN CHOICE.CHOICE_NO IS '찜번호';
COMMENT ON COLUMN CHOICE.CHOICE_FNO IS '찜한피드';
COMMENT ON COLUMN CHOICE.CHOICE_MEMBER IS '찜하기누른유저';
COMMENT ON COLUMN CHOICE.CHOICE_STATUS IS '찜한상태';

-- CHAT_ROOM_JOIN 테이블
COMMENT ON COLUMN CHAT_ROOM_JOIN.CHAT_ROOM_NO IS '채팅방번호';
COMMENT ON COLUMN CHAT_ROOM_JOIN.CHAT_USER_NO IS '채팅방들어가는유저';


-- CHAT_ROOM 테이블
COMMENT ON COLUMN CHAT_ROOM.CHAT_ROOM_NO IS '채팅방번호';
COMMENT ON COLUMN CHAT_ROOM.CHAT_USER_NO IS '채팅방들어가는유저';
COMMENT ON COLUMN CHAT_ROOM.CHAT_TITLE IS '채팅방제목';
COMMENT ON COLUMN CHAT_ROOM.STATUS IS '채팅방상태';


-- CHAT_MESSAGE 테이블
COMMENT ON COLUMN CHAT_MESSAGE.CHAT_NO IS '채팅번호';
COMMENT ON COLUMN CHAT_MESSAGE.CHAT_ROOM_NO IS '채팅방번호';
COMMENT ON COLUMN CHAT_MESSAGE.CHAT_USER_NO IS '채팅치는유저';
COMMENT ON COLUMN CHAT_MESSAGE.CHAT_MESSAGE IS '채팅메세지';
COMMENT ON COLUMN CHAT_MESSAGE.ENROLL_DATE IS '채팅치는시간';
COMMENT ON COLUMN CHAT_MESSAGE.FEED_NO IS '채팅게시물번호';


/* 제약조건 */ --필요한가 체크
ALTER TABLE MEMBER
ADD UNIQUE(USER_ID);

ALTER TABLE MEMBER
ADD UNIQUE(USER_NICK);

ALTER TABLE MEMBER
ADD UNIQUE(USER_NAME);

ALTER TABLE MEMBER
ADD UNIQUE(USER_EMAIL);

ALTER TABLE MEMBER
ADD UNIQUE(USER_PHONE);

COMMIT;